### PR TITLE
[BACKLOG-6638] - encoding connection name on delete

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by kurtwalker** [comment]
@rfellows @pminutillo @DFieldFL please review

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java
  src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java
  src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java
1. Message: Using a static member import should be avoided - org.pentaho.di.core.Const.nullToEmpty. at Line: 61 Column: None









Unit test coverage change:
============
org.pentaho.di.job.entries.publish.JobEntryDatasourcePublish:
 * instructionPercentCoverageChange : +0.02%
    
org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish:
 * instructionPercentCoverageChange : +3.54%
 * linePercentCoverageChange : +3.76%
 * complexityPercentCoverageChange : +7.59%
 * methodPercentCoverageChange : +17.35%

**Comment by rfellows** [comment]
@kurtwalker looks like you get to fix someone else's checkstyle violation.

**Comment by kurtwalker** [comment]
@rfellows I probably put it there to begin with.  I like using static imports, not sure why it's against the rules.  Either way, commit added that removes them

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java
  src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java
  src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java










Unit test coverage change:
============
org.pentaho.di.job.entries.publish.JobEntryDatasourcePublish:
 * instructionPercentCoverageChange : +0.02%
    
org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish:
 * instructionPercentCoverageChange : +3.54%
 * linePercentCoverageChange : +3.76%
 * complexityPercentCoverageChange : +7.59%
 * methodPercentCoverageChange : +17.35%

**Pull request merged**
