### PR TITLE
BACKLOG-7062--Adding an existing group throws unrelated warning messa…

### PR DESCRIPTION
**Pull request by kolinus**
…ges -

failing to load the existing group

What was done:
1) fix implemented

### CODE REVIEW

**Comment by kolinus** [comment]
@pminutillo @DFieldFL  @kurtwalker  @rfellows could you please take a look

**Comment by kurtwalker** [comment]
@kolinus can you give a quick explanation of when/why the event would be null?

**Comment by kolinus** [comment]
@kurtwalker  https://github.com/kolinus/pentaho-data-refinery/blob/7b8d97051fd5a70bb5b05385f339ea6fb7d25b55/src/main/java/org/pentaho/di/ui/trans/steps/annotation/BaseAnnotationStepDialog.java#L278

**Comment by kurtwalker** [comment]
:+1:

**Pull request merged**
