### PR TITLE
[BACKLOG-2842] - removing reference to meta store from error messages

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by kurtwalker** [comment]
@pminutillo @DFieldFL @rfellows changing message per ux feedback

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties

Newly Broken Tests:
======================
org.pentaho.di.trans.steps.annotation.ModelAnnotationStepTest.testMetaStoreAnnotationGroupNotThere:
-----------------------------------------------
org.junit.ComparisonFailure
```
org.junit.ComparisonFailure: expected:<...meGroup is not found[ in meta store].> but was:<...meGroup is not found[].>
	at org.pentaho.di.trans.steps.annotation.ModelAnnotationStepTest.testMetaStoreAnnotationGroupNotThere(ModelAnnotationStepTest.java:159)

```
org.pentaho.di.trans.steps.annotation.ModelAnnotationStepTest.testMetaStoreSharedDimensionNotThere:
-----------------------------------------------
org.junit.ComparisonFailure
```
org.junit.ComparisonFailure: expected:<...meGroup is not found[ in meta store].> but was:<...meGroup is not found[].>
	at org.pentaho.di.trans.steps.annotation.ModelAnnotationStepTest.testMetaStoreSharedDimensionNotThere(ModelAnnotationStepTest.java:191)

```

null

null

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

null

null

License header violations:
==========================
1. Copyright year is not the current year on src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java. Found 2015. Was expecting 2016

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

null

null

**Comment by kurtwalker** [comment]
@DFieldFL @rfellows @pminutillo

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

null

null

**Pull request merged**
