### PR TITLE
[BACKLOG-7852] - UI support for CreateAttribute formatString

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/ui/trans/steps/annotation/ModelAnnotationActionPropertiesDialog.java
  src/main/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolver.java
  src/test/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolverTest.java

Unit test coverage change:
============
org.pentaho.di.core.refinery.DataProviderHelper:
 * Branch Change : **-46.15%**
 * Complexity Change : **-53.85%**
 * Instruction Change : **-80.71%**
 * Line Change : **-77.42%**
 * Method Change : **-81.82%**

org.pentaho.di.core.refinery.DataProviderHelper.OutputStepMappingAdapter:
 * Branch Change : **-50.00%**
 * Complexity Change : **-50.00%**
 * Instruction Change : **-83.87%**
 * Line Change : **-88.89%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.DataRefineryConfig:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.extension.DataRefineryTransFinishListener:
 * Branch Change : **-80.56%**
 * Complexity Change : **-73.08%**
 * Instruction Change : **-80.70%**
 * Line Change : **-80.82%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.AnalysisModeler:
 * Branch Change : **-96.43%**
 * Complexity Change : **-92.86%**
 * Instruction Change : **-89.83%**
 * Line Change : **-86.52%**
 * Method Change : **-92.86%**

org.pentaho.di.core.refinery.model.DswModeler:
 * Branch Change : **-82.86%**
 * Complexity Change : **-76.67%**
 * Instruction Change : **-96.97%**
 * Line Change : **-96.36%**
 * Method Change : **-92.00%**

org.pentaho.di.core.refinery.model.DswModeler.ColumnKey:
 * Branch Change : **-50.00%**
 * Complexity Change : **-31.25%**
 * Instruction Change : **-76.14%**
 * Line Change : **-72.22%**
 * Method Change : **-71.43%**

org.pentaho.di.core.refinery.model.DswModeler.ColumnMismatchException:
 * Complexity Change : **-33.33%**
 * Instruction Change : **-40.00%**
 * Line Change : **-60.00%**
 * Method Change : **-33.33%**

org.pentaho.di.core.refinery.model.DswModeler.ModelingException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.GeoContextBlueprintConfigProvider:
 * Branch Change : **-83.33%**
 * Complexity Change : **-85.71%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.ModelServerFetcher:
 * Branch Change : **-50.00%**
 * Complexity Change : **-44.44%**
 * Instruction Change : **-62.27%**
 * Line Change : **-72.88%**
 * Method Change : **-87.50%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.AuthorizationException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.DataSourceType:
 * Branch Change : **-50.00%**
 * Complexity Change : **-44.44%**
 * Instruction Change : **-86.24%**
 * Line Change : **-100.00%**
 * Method Change : **-66.67%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.ServerException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.RefineryModelerWorkspaceHelper:
 * Branch Change : **-50.00%**
 * Complexity Change : **-30.00%**
 * Instruction Change : **-44.54%**
 * Line Change : **-43.75%**
 * Method Change : **-33.33%**

org.pentaho.di.core.refinery.model.RefineryValueMetaStrategy:
 * Branch Change : **-90.00%**
 * Complexity Change : **-87.50%**
 * Instruction Change : **-94.64%**
 * Line Change : **-90.91%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.agilebi.BiServerConnection:
 * Branch Change : **-83.33%**
 * Complexity Change : **-68.75%**
 * Instruction Change : **-82.28%**
 * Line Change : **-76.92%**
 * Method Change : **-69.23%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerAction:
 * Branch Change : **-83.33%**
 * Complexity Change : **-70.59%**
 * Instruction Change : **-74.65%**
 * Line Change : **-81.82%**
 * Method Change : **-71.43%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish:
 * Branch Change : **-83.33%**
 * Complexity Change : **-78.05%**
 * Instruction Change : **-90.31%**
 * Line Change : **-92.16%**
 * Method Change : **-82.35%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish.new Object() {...}:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-89.47%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.DataSourceAclModel:
 * Branch Change : **-90.00%**
 * Complexity Change : **-88.89%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.DataSourcePublishModel:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.ResponseStatus:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.RunInPluginClassLoader:
 * Branch Change : **-70.00%**
 * Complexity Change : **-57.14%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.BaseRestUtil:
 * Branch Change : **-80.00%**
 * Complexity Change : **-81.25%**
 * Instruction Change : **-84.89%**
 * Line Change : **-93.44%**
 * Method Change : **-90.91%**

org.pentaho.di.core.refinery.publish.util.JAXBUtils:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.ObjectUtils:
 * Branch Change : **-100.00%**
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.PublishRestUtil:
 * Branch Change : **-96.67%**
 * Complexity Change : **-96.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.job.entries.build.DataServiceConnectionInformation:
 * Branch Change : **-100.00%**
 * Complexity Change : **-100.00%**
 * Instruction Change : **-96.53%**
 * Line Change : **-94.74%**
 * Method Change : **-100.00%**

org.pentaho.di.job.entries.build.JobEntryBuildModel:
 * Branch Change : **-69.35%**
 * Complexity Change : **-68.75%**
 * Instruction Change : **-68.18%**
 * Line Change : **-70.16%**
 * Method Change : **-79.59%**

org.pentaho.di.job.entries.publish.JobEntryDatasourcePublish:
 * Branch Change : **-73.15%**
 * Complexity Change : **-71.60%**
 * Instruction Change : **-86.56%**
 * Line Change : **-86.10%**
 * Method Change : **-92.59%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationMeta:
 * Branch Change : **-56.58%**
 * Complexity Change : **-56.25%**
 * Instruction Change : **-74.17%**
 * Line Change : **-78.01%**
 * Method Change : **-92.31%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationMeta.new KeyValueClosure() {...}:
 * Branch Change : **-50.00%**
 * Complexity Change : **-50.00%**
 * Instruction Change : **-88.24%**
 * Line Change : **-75.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationStep:
 * Branch Change : **-88.89%**
 * Complexity Change : **-83.78%**
 * Instruction Change : **-91.61%**
 * Line Change : **-92.75%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.SharedDimensionGroupValidation:
 * Branch Change : **-90.91%**
 * Complexity Change : **-90.00%**
 * Instruction Change : **-81.01%**
 * Line Change : **-80.85%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.SharedDimensionGroupValidation.new Object() {...}:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-88.46%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.util.TransUtil:
 * Branch Change : **-91.67%**
 * Complexity Change : **-80.00%**
 * Instruction Change : **-87.61%**
 * Line Change : **-87.50%**
 * Method Change : **-75.00%**

org.pentaho.di.ui.job.entries.common.ConnectionValidator:
 * Branch Change : **-81.58%**
 * Complexity Change : **-73.53%**
 * Instruction Change : **-80.90%**
 * Line Change : **-80.26%**
 * Method Change : **-86.67%**

org.pentaho.di.ui.trans.steps.annotation.OptionsResolver:
 * Branch Change : **-85.00%**
 * Complexity Change : **-79.31%**
 * Instruction Change : **-96.69%**
 * Line Change : **-93.75%**
 * Method Change : **-100.00%**

org.pentaho.di.ui.trans.steps.common.ModelAnnotationEvent:
 * Complexity Change : **-75.00%**
 * Instruction Change : **-71.43%**
 * Line Change : **-66.67%**
 * Method Change : **-75.00%**

License header violations:
==========================
1. Copyright year is not the current year on src/main/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolver.java. Found 2015. Was expecting 2016
2. Copyright year is not the current year on src/test/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolverTest.java. Found 2015. Was expecting 2016

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/ui/trans/steps/annotation/ModelAnnotationActionPropertiesDialog.java
  src/main/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolver.java
  src/test/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolverTest.java

Unit test coverage change:
============
org.pentaho.di.core.refinery.DataProviderHelper:
 * Branch Change : **-46.15%**
 * Complexity Change : **-53.85%**
 * Instruction Change : **-80.71%**
 * Line Change : **-77.42%**
 * Method Change : **-81.82%**

org.pentaho.di.core.refinery.DataProviderHelper.OutputStepMappingAdapter:
 * Branch Change : **-50.00%**
 * Complexity Change : **-50.00%**
 * Instruction Change : **-83.87%**
 * Line Change : **-88.89%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.DataRefineryConfig:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.extension.DataRefineryTransFinishListener:
 * Branch Change : **-80.56%**
 * Complexity Change : **-73.08%**
 * Instruction Change : **-80.70%**
 * Line Change : **-80.82%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.AnalysisModeler:
 * Branch Change : **-96.43%**
 * Complexity Change : **-92.86%**
 * Instruction Change : **-89.83%**
 * Line Change : **-86.52%**
 * Method Change : **-92.86%**

org.pentaho.di.core.refinery.model.DswModeler:
 * Branch Change : **-82.86%**
 * Complexity Change : **-76.67%**
 * Instruction Change : **-96.97%**
 * Line Change : **-96.36%**
 * Method Change : **-92.00%**

org.pentaho.di.core.refinery.model.DswModeler.ColumnKey:
 * Branch Change : **-50.00%**
 * Complexity Change : **-31.25%**
 * Instruction Change : **-76.14%**
 * Line Change : **-72.22%**
 * Method Change : **-71.43%**

org.pentaho.di.core.refinery.model.DswModeler.ColumnMismatchException:
 * Complexity Change : **-33.33%**
 * Instruction Change : **-40.00%**
 * Line Change : **-60.00%**
 * Method Change : **-33.33%**

org.pentaho.di.core.refinery.model.DswModeler.ModelingException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.GeoContextBlueprintConfigProvider:
 * Branch Change : **-83.33%**
 * Complexity Change : **-85.71%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.ModelServerFetcher:
 * Branch Change : **-50.00%**
 * Complexity Change : **-44.44%**
 * Instruction Change : **-62.27%**
 * Line Change : **-72.88%**
 * Method Change : **-87.50%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.AuthorizationException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.DataSourceType:
 * Branch Change : **-50.00%**
 * Complexity Change : **-44.44%**
 * Instruction Change : **-86.24%**
 * Line Change : **-100.00%**
 * Method Change : **-66.67%**

org.pentaho.di.core.refinery.model.ModelServerFetcher.ServerException:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.model.RefineryModelerWorkspaceHelper:
 * Branch Change : **-50.00%**
 * Complexity Change : **-30.00%**
 * Instruction Change : **-44.54%**
 * Line Change : **-43.75%**
 * Method Change : **-33.33%**

org.pentaho.di.core.refinery.model.RefineryValueMetaStrategy:
 * Branch Change : **-90.00%**
 * Complexity Change : **-87.50%**
 * Instruction Change : **-94.64%**
 * Line Change : **-90.91%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.agilebi.BiServerConnection:
 * Branch Change : **-83.33%**
 * Complexity Change : **-68.75%**
 * Instruction Change : **-82.28%**
 * Line Change : **-76.92%**
 * Method Change : **-69.23%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerAction:
 * Branch Change : **-83.33%**
 * Complexity Change : **-70.59%**
 * Instruction Change : **-74.65%**
 * Line Change : **-81.82%**
 * Method Change : **-71.43%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish:
 * Branch Change : **-83.33%**
 * Complexity Change : **-78.05%**
 * Instruction Change : **-90.31%**
 * Line Change : **-92.16%**
 * Method Change : **-82.35%**

org.pentaho.di.core.refinery.publish.agilebi.ModelServerPublish.new Object() {...}:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-89.47%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.DataSourceAclModel:
 * Branch Change : **-90.00%**
 * Complexity Change : **-88.89%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.DataSourcePublishModel:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.model.ResponseStatus:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.RunInPluginClassLoader:
 * Branch Change : **-70.00%**
 * Complexity Change : **-57.14%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.BaseRestUtil:
 * Branch Change : **-80.00%**
 * Complexity Change : **-81.25%**
 * Instruction Change : **-84.89%**
 * Line Change : **-93.44%**
 * Method Change : **-90.91%**

org.pentaho.di.core.refinery.publish.util.JAXBUtils:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.ObjectUtils:
 * Branch Change : **-100.00%**
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.core.refinery.publish.util.PublishRestUtil:
 * Branch Change : **-96.67%**
 * Complexity Change : **-96.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.job.entries.build.DataServiceConnectionInformation:
 * Branch Change : **-100.00%**
 * Complexity Change : **-100.00%**
 * Instruction Change : **-96.53%**
 * Line Change : **-94.74%**
 * Method Change : **-100.00%**

org.pentaho.di.job.entries.build.JobEntryBuildModel:
 * Branch Change : **-69.35%**
 * Complexity Change : **-68.75%**
 * Instruction Change : **-68.18%**
 * Line Change : **-70.16%**
 * Method Change : **-79.59%**

org.pentaho.di.job.entries.publish.JobEntryDatasourcePublish:
 * Branch Change : **-73.15%**
 * Complexity Change : **-71.60%**
 * Instruction Change : **-86.56%**
 * Line Change : **-86.10%**
 * Method Change : **-92.59%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationMeta:
 * Branch Change : **-56.58%**
 * Complexity Change : **-56.25%**
 * Instruction Change : **-74.17%**
 * Line Change : **-78.01%**
 * Method Change : **-92.31%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationMeta.new KeyValueClosure() {...}:
 * Branch Change : **-50.00%**
 * Complexity Change : **-50.00%**
 * Instruction Change : **-88.24%**
 * Line Change : **-75.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.ModelAnnotationStep:
 * Branch Change : **-88.89%**
 * Complexity Change : **-83.78%**
 * Instruction Change : **-91.61%**
 * Line Change : **-92.75%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.SharedDimensionGroupValidation:
 * Branch Change : **-90.91%**
 * Complexity Change : **-90.00%**
 * Instruction Change : **-81.01%**
 * Line Change : **-80.85%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.annotation.SharedDimensionGroupValidation.new Object() {...}:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-88.46%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.util.TransUtil:
 * Branch Change : **-91.67%**
 * Complexity Change : **-80.00%**
 * Instruction Change : **-87.61%**
 * Line Change : **-87.50%**
 * Method Change : **-75.00%**

org.pentaho.di.ui.job.entries.common.ConnectionValidator:
 * Branch Change : **-81.58%**
 * Complexity Change : **-73.53%**
 * Instruction Change : **-80.90%**
 * Line Change : **-80.26%**
 * Method Change : **-86.67%**

org.pentaho.di.ui.trans.steps.annotation.OptionsResolver:
 * Branch Change : **-85.00%**
 * Complexity Change : **-79.31%**
 * Instruction Change : **-96.69%**
 * Line Change : **-93.75%**
 * Method Change : **-100.00%**

org.pentaho.di.ui.trans.steps.common.ModelAnnotationEvent:
 * Complexity Change : **-75.00%**
 * Instruction Change : **-71.43%**
 * Line Change : **-66.67%**
 * Method Change : **-75.00%**

**Comment by kurtwalker** [comment]
@pminutillo @rfellows @DFieldFL please review

**Comment by kurtwalker** [comment]
@pminutillo @rfellows @DFieldFL

**Pull request merged**
