### PR TITLE
[BACKLOG-9926] move annotation to init

### PR DESCRIPTION
**Pull request by tgf**

### CODE REVIEW

**Comment by kurtwalker** [comment]
Please make sure to rerun all the tests related to meta-injection of annotate stream and of shared dimension.  especially using both in the same transformation.

**Comment by tgf** [comment]
@kurtwalker any tests in particular?

**Comment by kurtwalker** [comment]
Valia should be able to point at all the spira tests.

**Comment by rfellows** [comment]
Looks like you might need a different version of xalan for your test scope. based on the test failures

**Comment by tgf** [comment]
@rfellows yes, this started happening when modeler was mavenized and was mavenized http://devci.pentaho.com/job/master-snapshot/job/pdi-data-refinery-plugin/81/

**Comment by rfellows** [comment]
Yeah, @kolinus is working on that still. but in the meantime, you can add that dependency to your pom

**Comment by tgf** [comment]
@rfellows i added a similar change, locally; those tests will pass once this is fixed
seems out of scope to add it here when a fix is being worked on

**Comment by mdamour1976** [comment]
As an update before I merge this, @tgf successfully ran the SpiraTest (15015) for this.

**Pull request merged**
