### PR TITLE
[BACKLOG-2842] - using different error messages for annotation group …

### PR DESCRIPTION
**Pull request by kurtwalker**
…vs shared dimension

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStep.java
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.annotation.ModelAnnotationStep:
 * Branch Change :  + .43%
 * Complexity Change :  + .45%
 * Instruction Change :  + .14%
 * Line Change :  + .11%

null

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStep.java

1. Message: Using a static member import should be avoided - org.pentaho.di.job.entries.build.JobEntryBuildModel.KEY_MODEL_ANNOTATIONS. at Line: 34

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStep.java
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.annotation.ModelAnnotationStep:
 * Branch Change :  + .43%
 * Complexity Change :  + .45%
 * Instruction Change :  + .14%
 * Line Change :  + .11%

null

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStep.java

1. Message: Using a static member import should be avoided - org.pentaho.di.job.entries.build.JobEntryBuildModel.KEY_MODEL_ANNOTATIONS. at Line: 34

**Comment by kurtwalker** [comment]
@DFieldFL @pminutillo @rfellows please review.  Note I corrected the checkstyle error, but wingman didn't pick up the new change I guess

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStep.java
  src/main/resources/org/pentaho/di/trans/steps/annotation/messages/messages_en_US.properties
  src/test/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationStepTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.annotation.ModelAnnotationStep:
 * Branch Change :  + .43%
 * Complexity Change :  + .45%
 * Instruction Change :  + .14%
 * Line Change :  + .11%

null

**Pull request merged**
